runtime: python27
api_version: 1
threadsafe: yes

inbound_services:
- mail

handlers:
- url: /_ah/queue/deferred
  script: djangoappengine.deferred.handler.application
  login: admin

- url: /_ah/mail/.+
  script: djangoappengine.main.application
  login: admin

- url: /.well-known
  static_dir: well-known

- url: /static
  static_dir: emailhooks/static
  secure: always

- url: /.*
  script: djangoappengine.main.application
  secure: always

automatic_scaling:
  max_idle_instances: 1
  min_pending_latency: 2000ms
  max_pending_latency: 5000ms
  max_concurrent_requests: 80
