application: emailization
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

inbound_services:
- warmup
- mail

libraries:
- name: django
  version: latest

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /_ah/queue/deferred
  script: djangoappengine.deferred.handler.application
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine.appstats.application

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'
  
- url: /static   
  static_dir: static

- url: /.*
  script: djangoappengine.main.application
